services:
    collector:
        env_file:
            - path: .env
              required: true
        volumes:
            - ./out:/out
        image: thegeeklab/prometheus-pve-sd
    exporter:
        depends_on: 
          - prometheus-pve-sd
        image: php:8.2-apache
        ports:
            - 8081:80
        volumes:
            - ./out:/out
            - ./metrics:/var/www/html/metrics
