services:
    collector:
        image: thegeeklab/prometheus-pve-sd
        env_file: .env
        restart: unless-stopped
        volumes:
            - ./out:/out
    exporter:
        image: php:8.2-apache
        restart: unless-stopped
        depends_on:
          - collector
        ports:
            - 8081:80
        volumes:
            - ./out:/out
            - ./metrics:/var/www/html/metrics
