services:
    permissions-fix:
        image: centos
        volumes:
            - ./out:/out
            - ./metrics:/metrics
        command: bash -c "touch /out/metrics.json && chmod +r -R /out && chmod +r -R /metrics"
    prometheus-pve-sd:
        depends_on: 
          - permissions-fix
        env_file:
            - path: .env
              required: true
        volumes:
            - ./out:/out
        image: thegeeklab/prometheus-pve-sd
    prometheus-pve-sd-web:
        depends_on: 
          - prometheus-pve-sd
        image: php:8.2-apache
        ports:
            - 8081:80
        volumes:
            - ./out:/out
            - ./metrics:/var/www/html/metrics
